# Generated by Django 5.2.6 on 2025-10-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalBlog', '0002_comment_rename_author_post_author_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
