# Generated by Django 5.2.6 on 2025-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalBlog', '0007_profile_delete_comment_remove_post_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('PersonalBlog', 'Blog Post'), ('journal', 'Journal Entry')], default='PersonalBlog', max_length=50),
        ),
    ]
